name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./arquibancada-cblow 

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: './arquibancada-cblow/pnpm-lock.yaml'

      - name: Instalar Dependências
        run: pnpm install

      - name: Gerar Build
        run: pnpm run build

      - name: Enviar para a VPS (Rsync)
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "arquibancada-cblow/build/" 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/var/www/arquibancada-cblow/"